# Gradle
org.gradle.jvmargs=-Xmx8g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=false
org.gradle.configuration-cache=true
# Android
android.useAndroidX=true
android.nonTransitiveRClass=true
android.r8.gradual.support=true
android.r8.maxWorkers=4
android.suppressUnsupportedCompileSdk=37.0

# Kotlin
kotlin.code.style=official

systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7890
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7890
