[versions]
agp = "9.2.1"
eddsa = "0.3.0"
kotlin = "2.4.0"
kotlinxDatetimeVersion = "0.8.0"
ksp = "2.3.9"
aboutlibraries = "15.0.3"
readability4j = "1.0.8"
webview = "0.33.6"
gson = "3.0.0"
scalars = "3.0.0"
coreSplashscreen = "1.2.0"
datastore = "1.2.1"
hiltAndroid = "2.60"
hiltNavigationCompose = "1.4.0"
konfetti = "2.0.5"
material = "1.11.4"
materialKolor = "4.1.1"
materialIconsCore = "1.7.8"
nav3 = "1.1.4"
jsoup = "1.22.2"
coreKtx = "1.19.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
coroutines = "1.11.0"
serialization = "1.11.0"
lifecycleRuntimeKtx = "2.11.0"
lifecycleViewmodelNav3 = "2.11.0"
activityCompose = "1.13.0"
composeBom = "2026.06.01"
miuix = "0.9.3"
navigationCompose = "2.9.8"
coil = "3.5.0"
appcompat = "1.7.1"
retrofit = "3.0.0"
webkit = "1.16.0"
vico = "3.2.3"
zoomableCoil3 = "0.19.0"

[libraries]
about-library = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutlibraries" }
kotlin-metadata-jvm = { module = "org.jetbrains.kotlin:kotlin-metadata-jvm", version.ref = "kotlin" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetimeVersion" }
androidx-material-icons-core = { module = "androidx.compose.material:material-icons-core", version.ref = "materialIconsCore" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsCore" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }

androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodelNav3" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-navigation3-runtime = { group = "androidx.navigation3", name = "navigation3-runtime", version.ref = "nav3" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "material" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "material" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "material" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "material" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "material" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "material" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }

miuix-ui = { module = "top.yukonga.miuix.kmp:miuix-ui-android", version.ref = "miuix" }
miuix-preference = { module = "top.yukonga.miuix.kmp:miuix-preference-android", version.ref = "miuix" }
miuix-icons = { module = "top.yukonga.miuix.kmp:miuix-icons-android", version.ref = "miuix" }
miuix-blur = { module = "top.yukonga.miuix.kmp:miuix-blur-android", version.ref = "miuix" }
miuix-navigation3-ui = { module = "top.yukonga.miuix.kmp:miuix-navigation3-ui-android", version.ref = "miuix" }
miuix-squircle = { module = "top.yukonga.miuix.kmp:miuix-squircle-android", version.ref = "miuix" }
miuix-shader = { module = "top.yukonga.miuix.kmp:miuix-shader-android", version.ref = "miuix" }

readability4j = { module = "net.dankito.readability4j:readability4j", version.ref = "readability4j" }
zoomable-image-coil3 = { module = "me.saket.telephoto:zoomable-image-coil3", version.ref = "zoomableCoil3" }
webview = { module = "io.github.kevinnzou:compose-webview", version.ref = "webview" }
konfetti = { module = "nl.dionsegijn:konfetti-compose", version.ref = "konfetti" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltAndroid" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "scalars" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "gson" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

vico = { group = "com.patrykandpatrick.vico", name = "compose-m3", version.ref = "vico" }

eddsa = { module = "net.i2p.crypto:eddsa", version.ref = "eddsa" }

material-kolor = { group = "com.materialkolor", name = "material-kolor", version.ref = "materialKolor" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
about-library = { id = "com.mikepenz.aboutlibraries.plugin.android", version.ref = "aboutlibraries" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
