package com.smart.htu.screens.navigation

sealed class Destinations(
    val route: String
) {
    data object App : Destinations("main")
    data object Login : Destinations("login")
    data object News : Destinations("news")
    data object Person : Destinations("person")
    data object Application : Destinations("application")
    data object NewsSearch : Destinations("news_search")
    data object NewsHistory : Destinations("news_history")
    data object NewsDetail : Destinations("news_detail")
    data object ApplicationEdit : Destinations("application_edit")
    data object Message : Destinations("message")
    data object Setting : Destinations("setting")
    data object About : Destinations("about")
    data object ClassroomSearch : Destinations("classroom_search")
    data object ApplicationWebView : Destinations("application_webview")
    data object License : Destinations("license")
    data object LibrarySearch : Destinations("library_search")
    data object LibrarySearchDetail : Destinations("library_search_detail")
    data object AirCondition : Destinations("air_condition")
    data object AirConditionSetting : Destinations("air_condition_setting")
    data object AccountManage : Destinations("account_manage")
    data object Grade : Destinations("grade")
    data object TeacherEvaluation : Destinations("teacher_evaluation")
    data object TeacherEvaluationDetail : Destinations("teacher_evaluation_detail")
    data object Textbook : Destinations("textbook")
    data object TextbookSelect : Destinations("textbook_select")
    data object CourseTable : Destinations("course_table")
    data object Feedback : Destinations("feedback")
    data object WebsiteNavigation : Destinations("website_navigation")
    data object AIConfiguration : Destinations("ai_configuration")
    data object HomeContentSettings : Destinations("home_content_settings")
    data object PhysicalTest : Destinations("physical_test")
    data object PdfReaderView : Destinations("pdf_viewer")
    data object MessageBoard : Destinations("message_board")
    data object MessageBoardDetail : Destinations("message_board_detail")
    data object CampusLife : Destinations("campus_life")
    data object ArticleStyle : Destinations("article_style")
    data object TaskManager: Destinations("task_manager")
    data object AddExamSchedule: Destinations("add_exam_schedule")
    data object SecondClass: Destinations("second_class")
    data object CourseHelperNavHost: Destinations("course_helper_nav_host")
    data object CourseHelper: Destinations("course_helper")
    data object CourseRepo: Destinations("course_repo")
    data object CourseInfo: Destinations("course_info")
    data object CourseSearchNavHost: Destinations("course_search_nav_host")
    data object CourseSearch: Destinations("course_search")
    data object CourseSearchRepo: Destinations("course_search_repo")
}