name: Android CI

# 触发器
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    # 设置jdk环境为1.8
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # 打包release
      - name: Build with Gradle
        run: bash ./gradlew assembleRelease
