name: Build

on:
  push:
    branches:
      - v3
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7

      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Decode keystore
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 -d > release.keystore

      - name: Build Release APK
        run: ./gradlew assembleRelease
        env:
          KEYSTORE_PATH: release.keystore
          KEY_ALIAS: ${{ secrets.ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}

      - name: List files in the release directory for debugging
        run: ls ./app/build/outputs/apk/release/

      - name: Check tag
        id: check_tag
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "IS_TAG=true" >> $GITHUB_OUTPUT
            echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "IS_TAG=false" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        if: steps.check_tag.outputs.IS_TAG == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.check_tag.outputs.TAG_NAME }}
          name: Release ${{ steps.check_tag.outputs.TAG_NAME }}
          files: app/build/outputs/apk/release/*.apk
          generate_release_notes: true
          body: |
            ${{ github.event.head_commit.message }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Post to Telegram ci channel
        env:
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          COMMIT_MESSAGE: |
            New CI from SmartHNU

            ```
            ${{ github.event.head_commit.message }}
            ```
        run: |
          if [ ! -z "${BOT_TOKEN}" ]; then
            if [ ! -z "${CHANNEL_ID}" ]; then
              export RELEASE=$(find ./app/build/outputs/apk/release -name "*.apk" | head -n 1)
              echo "Debug: RELEASE path is $RELEASE"

              if [ -f "$RELEASE" ]; then
                ESCAPED=$(python3 -c 'import json,os,urllib.parse; print(urllib.parse.quote(json.dumps(os.environ["COMMIT_MESSAGE"])))')
                curl -v "https://api.telegram.org/bot${BOT_TOKEN}/sendMediaGroup?chat_id=${CHANNEL_ID}&media=%5b%7b%22type%22%3a%22document%22%2c+%22media%22%3a%22attach%3a%2f%2frelease%22%2c%22parse_mode%22%3a%22MarkdownV2%22%2c%22caption%22%3a${ESCAPED}%7D%5D" -F release="@$RELEASE"
              else
                echo "Error: APK file not found at $RELEASE"
                exit 1
              fi
            fi
          fi