name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: sign_app
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Get tag name
        id: get_tag
        run: |
          TAG_NAME=$(echo "${GITHUB_REF}" | sed 's/refs\/tags\///')
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV

      - run: mv ${{steps.sign_app.outputs.signedReleaseFile}} SmartHNU_${{ env.TAG_NAME }}.apk
        env:
          TAG_NAME: ${{ env.TAG_NAME }}
      - uses: ncipollo/release-action@v1
        if: "! contains(github.ref, 'beta')"
        with:
          artifacts: "*.apk"
          token: ${{ github.token }}
          generateReleaseNotes: true

      - name: Post to Telegram ci channel
        env:
            CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
            BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
            COMMIT_MESSAGE: |+
              New CI from SmartHNU
              
              ```
              ${{ github.event.head_commit.message }}
              ```
        run: |
            if [ ! -z "${{ secrets.BOT_TOKEN }}" ]; then
          echo "Searching for APK files..."
              export RELEASE=$(find ./app/build/outputs/apk/release -name "*.apk")
          echo "Found APK: $RELEASE"
          ESCAPED=`python3 -c 'import json,os,urllib.parse; print(urllib.parse.quote(json.dumps(os.environ["COMMIT_MESSAGE"])))'`
          curl -v "https://api.telegram.org/bot${BOT_TOKEN}/sendMediaGroup?chat_id=${CHANNEL_ID}&media=%5B%7B%22type%22%3A%22document%22%2C%20%22media%22%3A%22attach%3A%2F%2Frelease%22%7D%2C%7B%22type%22%3A%22document%22%2C%20%22media%22%3A%22attach%3A%2F%2Fdebug%22%2C%22parse_mode%22%3A%22MarkdownV2%22%2C%22caption%22%3A${ESCAPED}%7D%5D" -F release="@$RELEASE"
            fi